package com.mycompany.restaurante;

import javax.swing.JOptionPane;

public class Ventana extends javax.swing.JFrame {

    Menu objetoMenu = new Menu();
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createMenu = new javax.swing.JButton();
        consultMenu = new javax.swing.JButton();
        enterData = new javax.swing.JButton();
        analizeInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ANALÍTICA DE DATOS UFPSO");

        createMenu.setText("Crear menú");
        createMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMenuActionPerformed(evt);
            }
        });

        consultMenu.setText("Consultar menú");
        consultMenu.setEnabled(false);
        consultMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultMenuActionPerformed(evt);
            }
        });

        enterData.setText("Ingresar datos");
        enterData.setEnabled(false);
        enterData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterDataActionPerformed(evt);
            }
        });

        analizeInfo.setText("Analizar información");
        analizeInfo.setEnabled(false);
        analizeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizeInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(createMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultMenu)
                        .addGap(18, 18, 18)
                        .addComponent(enterData)
                        .addGap(18, 18, 18)
                        .addComponent(analizeInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createMenu)
                    .addComponent(consultMenu)
                    .addComponent(enterData)
                    .addComponent(analizeInfo))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMenuActionPerformed
        objetoMenu.crearMenu(validateIntInput(JOptionPane.showInputDialog("Ingrese la cantidad de platos:")));
        consultMenu.setEnabled(true);
        enterData.setEnabled(true);
    }//GEN-LAST:event_createMenuActionPerformed

    private void consultMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultMenuActionPerformed
        JOptionPane.showMessageDialog(rootPane, objetoMenu.obtenerMenu());
    }//GEN-LAST:event_consultMenuActionPerformed

    private void enterDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterDataActionPerformed
        JOptionPane.showMessageDialog(rootPane, "A continuación deberá ingresar la cantidad de ventas de cada plato cada día de la semana.");
        objetoMenu.ingresarInfo();
        analizeInfo.setEnabled(true);
    }//GEN-LAST:event_enterDataActionPerformed

    private void analizeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizeInfoActionPerformed
        JOptionPane.showMessageDialog(rootPane, objetoMenu.analizarInfo());
    }//GEN-LAST:event_analizeInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    public int validateIntInput(String str) {
        while (isNumber(str)==false) {
            str = JOptionPane.showInputDialog("Ingrese un número ENTERO válido (sin espacios):");
        }
        return Integer.parseInt(str);
    }
    
    public static boolean isNumber(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizeInfo;
    private javax.swing.JButton consultMenu;
    private javax.swing.JButton createMenu;
    private javax.swing.JButton enterData;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
