package com.mycompany.academico;

import java.util.Arrays;
import javax.swing.JOptionPane;

public class Ventanaprincipal extends javax.swing.JFrame {
    
    int arrayMenores[];
    int arrayMayores[];
    int arrayAdultosMayores[];
    int menor = 0;
    int mayor = 0;
    int adultomayor = 0;
    
    /**
     * Creates new form Ventanaprincipal
     */
    public Ventanaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        consultButton = new javax.swing.JButton();
        arraySizes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("SISTEMA ACADÉMICO");

        createButton.setText("Crear");
        createButton.setEnabled(false);
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        consultButton.setText("Consultar");
        consultButton.setEnabled(false);
        consultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultButtonActionPerformed(evt);
            }
        });

        arraySizes.setText("Tamaños");
        arraySizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arraySizesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(createButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consultButton)
                        .addGap(18, 18, 18)
                        .addComponent(arraySizes)))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultButton)
                    .addComponent(arraySizes))
                .addGap(224, 224, 224))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        
        
        int edad = validateIntInput(JOptionPane.showInputDialog(rootPane, "Ingrese su edad"));
        if (edad<18) {
            JOptionPane.showMessageDialog(rootPane,"Usted es menor de edad");
            if (menor == arrayMenores.length) {
                JOptionPane.showMessageDialog(rootPane,"No hay espacio en memoria para almacenar");
            } else {            
                arrayMenores[menor] = edad;
                menor++;
            }
        } else if (edad<60) {
            JOptionPane.showMessageDialog(rootPane,"Usted es un mayor de edad");
            if (mayor == arrayMayores.length) {
                JOptionPane.showMessageDialog(rootPane,"No hay espacio en memoria para almacenar");
            } else {
                arrayMayores[mayor] = edad;
                mayor++;
            }
        } else {
            JOptionPane.showMessageDialog(rootPane,"Usted es un adulto mayor");
            if (adultomayor == arrayAdultosMayores.length) {
                JOptionPane.showMessageDialog(rootPane,"No hay espacio en memoria para almacenar");
            } else {
                arrayAdultosMayores[adultomayor] = edad;
                adultomayor++;
            }
        }
        
        
    }//GEN-LAST:event_createButtonActionPerformed

    private void consultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultButtonActionPerformed
        JOptionPane.showMessageDialog(rootPane,"Menores: "+Arrays.toString(arrayMenores)+"\nAdultos: "+Arrays.toString(arrayMayores)+"\nAdultos Mayores: "+Arrays.toString(arrayAdultosMayores));
    }//GEN-LAST:event_consultButtonActionPerformed

    private void arraySizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arraySizesActionPerformed
        arrayMenores = new int[validateIntInput(JOptionPane.showInputDialog(rootPane, "Ingrese cantidad de menores:"))];
        arrayMayores = new int[validateIntInput(JOptionPane.showInputDialog(rootPane, "Ingrese cantidad de mayores:"))];
        arrayAdultosMayores = new int[validateIntInput(JOptionPane.showInputDialog(rootPane, "Ingrese cantidad de adultos mayores:"))];
        
        createButton.setEnabled(true);
        consultButton.setEnabled(true);
    }//GEN-LAST:event_arraySizesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanaprincipal().setVisible(true);
            }
        });
    }

    public int validateIntInput(String str) {
        while (isNumeric(str)==false) {
            str = JOptionPane.showInputDialog(rootPane, "Ingrese un número ENTERO válido (sin espacios):");
        }
        return Integer.parseInt(str);
    }
    
    public static boolean isNumeric(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arraySizes;
    private javax.swing.JButton consultButton;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
